### PR TITLE
[jsonapi] Allow adding items by query language to the queue (plus some small fixes)

### LINKED ISSUE #641: Compound JSON api search
@chme, I am playing around with voice control of forked-daapd using Google Home Mini and IFTTT, which makes it possible to add custom commands. I've got basic controls working, like for instance play/pause, volume and next. So next thing to try is commands like "play $something" and "enable speaker $name". It seems like Google will be able to voice-to-text $something and $name if they are English (and other major languages), and it can then make a web request to forked-daapd containing the values. However, it will only make a single request, so using the JSON api with search + add to queue + play is a bit difficult.

So I am thinking of adding parameters to the search api to not just search, but also queue and play the results, so it can be done in one request. Sort of like DACP's playqueue-edit. Does that sound ok to you?

### PR DESCRIPTION
**Pull request by chme**
- Allow adding new items to the queue by query language, add new optional parameters to start playback after adding new items (closes #641)
- Fix ordering of tracks in `library/files` endpoint
- Fix segfault if an empty `uris` parameter is passed to `queue/items/add` endpoint
- Include configured library directories in `config` endpoint
- Add missing "database" notification to `websocket.c`

### CODE REVIEW

**Comment by chme** [comment]
Squeezed another fix into this pr. We are missing the "database" notification in websockets.c. This notification is required to properly update the web interface in case the database changes.

File: src/httpd_jsonapi.c [hunk 1]
```diff
@@ -1827,16 +1803,99 @@ jsonapi_reply_queue_tracks_add(struct httpd_request *hreq)
       if (pos >= 0)
 	pos += count;
 
-      ttl_count += count;
+      *total_count += count;
     }
   while ((uri = strtok(NULL, ",")));
```
Comment (whatdoineed2do) [inline src/httpd_jsonapi.c]: small Q - shouldn't this be `strtok_r()` to avoid potential data-race across threads?  I see `strtok` being used in `http.c` whilst other files are using `strtok_r`

**Comment by chme** [comment]
This is now ready to be merged. @ejurgensen Would be great if you could take a quick look at it. I added the implementation for the proposal in #641. A query to start playback for a search string could look like 

```
curl -X POST "http://localhost:3689/api/queue/items/add?expression=artist+includes+\"xx\"&clear=true&shuffle=false&play=true"
```

File: src/httpd_jsonapi.c [hunk 2]
```diff
@@ -1812,16 +1825,117 @@ jsonapi_reply_queue_tracks_add(struct httpd_request *hreq)
...
+      DPRINTF(E_LOG, L_WEB, "Missing query parameter 'uris' or 'expression'\n");
+
+      return HTTP_BADREQUEST;
+    }
+
+  // if query parameter "clear" is "true", stop playback and clear the queue before adding new queue items
+  param = evhttp_find_header(hreq->query, "clear");
+  if (param && strcmp(param, "true") == 0)
+    {
+      player_playback_stop();
```
Comment (ejurgensen) [inline src/httpd_jsonapi.c]: Maybe have this in its own function, which can also be called by jsonapi_reply_queue_clear()? It would be to avoid the risk that some future coder makes a modification in jsonapi_reply_queue_clear() and forgets to make the same modification here.

File: src/httpd_jsonapi.c [hunk 3]
```diff
@@ -1830,6 +1944,13 @@ jsonapi_reply_queue_tracks_add(struct httpd_request *hreq)
   if (ret < 0)
     return HTTP_INTERNAL;
 
+  // If query parameter "play" is "true", start playback after successfully adding new items
```
Comment (ejurgensen) [inline src/httpd_jsonapi.c]: play=true sounds a bit odd to me, also taking into account that play=false wouldn't do the opposite. You could just look for "play" without any value? Or if you want to prepare for more playback control then maybe playback=start.
